### ISSUE TITLE
get the same video  when using different task name

### ISSUE THREAD

**Issue by xlsay** [facebookresearch/humenv#7]
def show_task(task):
    env, manager = make_humenv(
                    task = task, 
                )

    env.reset()
    frames = [env.render()]
    for i in range(60):
        env.step(env.action_space.sample())
        frames.append(env.render())
    media.show_video(frames, fps=30)
    env.close()

for task in humenv.STAND_TASKS:
    show_task(task)

Hi, Why do I get the same video  when using this script to view the humanoid behaviors of different tasks? Can you help?

**Comment by MateuszGuzek** [comment]
In your code snippet you just sample random actions from the action space. With the same random seed, you should get the same videos.
Task is related to the reward function. So you should see the same videos, but rewards / returns should differ.
In practice, to have different behaviors (so different videos), you should e.g. use a task-specific policy (standard RL), or a policy that can infer reward (like FB, FB-CPR in Meta Motivo).

**Comment by xlsay** [comment]
> In your code snippet you just sample random actions from the action space. With the same random seed, you should get the same videos. Task is related to the reward function. So you should see the same videos, but rewards / returns should differ. In practice, to have different behaviors (so different videos), you should e.g. use a task-specific policy (standard RL), or a policy that can infer reward (like FB, FB-CPR in Meta Motivo).

Thank you very much for your answers.
